POST https://tgey0zvmn7.execute-api.sa-east-1.amazonaws.com/live/movies
Content-Type: application/json

{
    "title": "My Super Movie",
    "genres": [
        "Adventure",
        "Sci-Fi"
    ],
    "rating": 8.0
}